services:
  database:
    image: pgvector/pgvector:pg16 
    container_name: nutri_db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nutri_php
    ports:
      - "8000:8000" # <-- ABRIMOS EL PUERTO AL EXTERIOR
    volumes:
      - .:/app
    depends_on:
      - database
    command: php -S 0.0.0.0:8000 -t public/


  frontend:
    image: node:20-alpine
    container_name: nutri_frontend
    working_dir: /app
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/app
    environment:
      # Conecta el frontend con tu backend en producción
      - NEXT_PUBLIC_API_URL=http://2.28.76.81:8000
    command: sh -c "npm install && npm run build && npm start"
    depends_on:
      - php

volumes:
  db_data: